### ISSUE TITLE
-u (uniq) option is unreliable

### ISSUE THREAD

**Issue by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [keenerd/gz-sort#3]
-u (uniq) option doesn't even work

**Comment by keenerd** [comment]
Yes. it does.

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
Nope. Compare.

$ echo -en '1\n2\n2\n3\n2\n' | sort -u
1
2
3

$ echo -en '1\n2\n2\n3\n2\n' | gzip > 1.gz

$ ./gz-sort -u 1.gz 2.gz             
removed 5 non-unique lines

$ zcat 2.gz                  
1
2
2
2
3

**Comment by keenerd** [comment]
Interesting.  It works with much larger inputs.

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
ok, -u (uniq) option is unreliable

**Comment by keenerd** [comment]
Thanks for the example.  It has been added to the test cases and fix in commit 339d979.

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
Nice! Thanks for the fix :)
